//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDeDatosD
{
    using System;
    
    public partial class sp_listado_comentarios_Result1
    {
        public int id_comentario { get; set; }
        public string comentario { get; set; }
        public Nullable<int> calificacion { get; set; }
        public string mejoras { get; set; }
    }
}
