//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDeDatosD
{
    using System;
    
    public partial class sp_Listado_Citas_Result1
    {
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdSucursal { get; set; }
    }
}
